comment: false
token:
  ad13e599-e55a-4d7f-b3a2-f54258ccf382

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
